spring:

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/postgres
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false

springdoc.swagger-ui:
    enabled: true

springdoc:
  paths-to-match: /auth/**

jwt:
  secret: ${SECRET_KEY}